### ISSUE TITLE
Parser pipelines are not new

### ISSUE THREAD

**Issue by link2xt** [elm/parser#17]
Comparison page says there are no parser pipelines in other libraries, but actually operators `|.` and `|=` are not different from `<*` and `<*>` defined for applicative functors in Haskell, so you can construct parser pipelines with Parsec. `succeed` is equivalent to `pure` and can be avoided with the use of `<$` and `<$>`. See https://ravichugh.gitbooks.io/a-quarter-of-haskell/parsing/more.html#parser-pipelines

**Comment by rlefevre** [comment]
Note that the article you linked to literally calls the "parser pipeline" pattern as borrowed from an **elm** library, linking to https://github.com/elm-tools/parser#parser-pipelines:
> Formatting this expression with newlines results in a nice "parser pipeline", a pattern borrowed from an Elm library, albeit with different operators:

My point of view is that parser operators already existed, but the **elm** way to present them vertically is what is called the "parser pipeline" pattern. In other words, as often, some new forms of expression are found from prior art, as expected. Not that it matters much, as the most important is how users make it worthwhile.
