### ISSUE TITLE
Is it worth to introduce `optionally`?

### ISSUE THREAD

**Issue by dvberkel** [elm/parser#27]
Dear maintainers of `elm/parser`,

First of all, thanks for your hard work. It is a very nice library. It could use some love here and there, so if you need some help, don't be shy to ask me.

I was creating [an example](https://github.com/dvberkel/elm-parser-example) to answer a question on slack and wanted to transform a `Parser a` into a `Parser (Maybe a)`. I was expecting to find an `optionally` but could not find anything similar in the package.

I implemented it like this

```elm
optionally : Parser a -> Parser (Maybe a)
optionally parser =
    oneOf
        [ parser |> map Just
        , succeed Nothing
        ]
```

Is this something that is interesting to provide through the package? And if so, is my implementation missing a use case?

Thanks in advance for considering my question. I hope the new year brings a lot of  joy.

**Comment by mauroc8** [comment]
The [map function](https://github.com/elm/parser/blob/master/src/Parser.elm#L372) has an example similar to yours:

    nullOrInt : Parser (Maybe Int)
    nullOrInt =
      oneOf
        [ map Just int
        , map (\_ -> Nothing) (keyword "null")
        ]
    -- run nullOrInt "0"    == Ok (Just 0)
    -- run nullOrInt "13"   == Ok (Just 13)
    -- run nullOrInt "null" == Ok Nothing
    -- run nullOrInt "zero" == Err ...

It's pretty straightforward to do this, so it's not necessary in the core package. It would be nice to have --though-- in a "Parser.Extra" package.

**Comment by dvberkel** [comment]
:+1:  Thanks for your answer
