### ISSUE TITLE
Example code imports non existing module

### ISSUE THREAD

**Issue by rl-king** [elm/parser#3]
This example https://alpha.elm-lang.org/packages/elm/parser/latest/Parser#sequence imports `Parser.LanguageKit`. I was making a PR but also saw not all examples have imports declared so wasn't sure what to do.

**Comment by evancz** [comment]
This should be fixed by https://github.com/elm/parser/commit/01e2fb70e49ada53cedd1e31fab061ef4da35d87

Thanks for letting me know about it!
