### ISSUE TITLE
Broken links in documentation

### ISSUE THREAD

**Issue by robx** [elm/parser#6]
The documentation for `backtrackable` at https://package.elm-lang.org/packages/elm/parser/latest/Parser#backtrackable points at the missing https://package.elm-lang.org/packages/elm/parser/latest/TODO. There are some more links like this on the same page.

**Comment by zenhack** [comment]
Also the link to `inContext` in the README:

https://github.com/elm/parser/blob/master/README.md#tracking-context

**Comment by jorgengranseth** [comment]
Also:
- `README` explains `delayedCommit` in detail and links to it in the docs, but I believe it has been replaced with `backtrackable`
- `README` has two `<br>` tags at the bottom which are displayed as plaintext on [package.elm-lang.org](https://package.elm-lang.org/packages/elm/parser/1.0.0/)
- `backtrackable` should link to `semantics.md`(?)
- there should be an example for `commit` (in `semantics.md`?) based on its documentation
- `Parser.Advanced` is referenced in the docs of `Parser` but not exposed in `elm.json`
