### ISSUE TITLE
expose Parser.Advanced

### ISSUE THREAD

**Issue by brandly** [elm/parser#8]
some docs seem to speak as though `Parser.Advanced` should be exposed

https://github.com/elm/parser/blob/828a7903226430e86eb644d89f49dd901990f79b/src/Parser.elm#L133-L134

but it isn't exposed

https://github.com/elm/parser/blob/828a7903226430e86eb644d89f49dd901990f79b/elm.json#L7-L9

**Comment by evancz** [comment]
I'm working on it! I wasn't able to get it out with the initial release of 0.19.
